# Generated by Django 5.2.3 on 2025-12-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
