# Generated by Django 3.2.23 on 2024-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bids_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(error_messages={'required': ''}, max_length=64),
        ),
    ]
