# Generated by Django 3.2.23 on 2024-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
