# Generated by Django 3.2.23 on 2024-02-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='createdBy',
            field=models.CharField(default=True, max_length=64),
            preserve_default=False,
        ),
    ]
