# Generated by Django 3.2.23 on 2024-02-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20240221_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(to='auctions.AuctionListing'),
        ),
    ]
