# Generated by Django 3.2.23 on 2024-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='auctions.AuctionListing'),
        ),
    ]
