# Generated by Django 3.2.23 on 2024-02-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20240221_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(blank=True, max_length=64, on_delete=django.db.models.deletion.CASCADE, to='auctions.category', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
