# Generated by Django 3.2.23 on 2024-02-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.user', unique=True),
            preserve_default=False,
        ),
    ]
