# Generated by Django 3.2.23 on 2024-02-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(blank=True, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.category'),
        ),
    ]
