# Generated by Django 3.2.23 on 2024-02-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(default=True, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='bidItem',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.auctionlisting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='bidUser',
            field=models.ForeignKey(default=True, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.user'),
            preserve_default=False,
        ),
    ]
