# Generated by Django 5.2.3 on 2025-06-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20240228_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bidstart_decimal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_decimal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
