# Generated by Django 5.2.3 on 2025-08-24 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_remove_bids_bid_decimal_alter_bids_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='createdBy',
            field=models.ForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
