# Generated by Django 5.2.3 on 2025-08-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_auctionlisting_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.category'),
        ),
    ]
